services:
  minitwit:
    container_name: MiniTwit
    build: ./
    ports: 
      - "5000:5000"
    env_file:
      - dev.env
    networks:
      - prom_net
      - db_net
    depends_on:
      db:
        condition: service_healthy

  minitwit-api:
    container_name: API
    build: 
      context: ./
      dockerfile: Dockerfile.api
    ports:
      - "5001:5001"
    env_file:
      - dev.env
    networks:
      - prom_net
      - db_net
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    build:
      context: ./
      dockerfile: Dockerfile.pg
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 3s
      timeout: 3s
      retries: 3

networks:
  db_net:
    name: db_net
    driver: bridge
    
  prom_net:
    name: prom_net
    driver: bridge