version: '3.8'

services:
  minitwit:
    image: minitwit:latest
    ports: 
      - "5000:5000"
    env_file:
      - dev.env
    networks:
      - minitwit

  minitwit-api:
    image: minitwit-api:latest
    ports:
      - "5001:5001"
    env_file:
      - dev.env
    networks:
      - minitwit

  db:
    image: postgres:alpine3.19
    env_file:
      - dev.env
    volumes:
      - ./utils/schema_postgres.sql:/docker-entrypoint-initdb.d/schema_postgres.sql 
    ports:
      - "5432:5432"
    networks:
      - minitwit

networks:
  minitwit:
    external:
      name: minitwit-network