services:

  minitwit:
    container_name: MiniTwit
    image: zelcam4ever/itu-minitwit:latest
    ports: 
      - 5000:5000
    env_file:
      - prod.env
    volumes:
      - ../secrets:/express-docker/secrets
    networks:
      - prom_net

  minitwit-api:
    container_name: API
    image: zelcam4ever/itu-minitwit-api:latest
    ports:
      - 5001:5001
    env_file:
      - prod.env
    volumes:
      - ../secrets:/express-docker/secrets

networks:
  prom_net:
    name: prom_net
    driver: bridge