version: '3.8'

services:
  minitwit:
    image: minitwit:latest
    ports: 
      - "5000:5000"
    env_file:
      - dev.env

  minitwit-api:
    image: minitwit-api:latest
    ports:
      - "5001:5001"
    env_file:
      - dev.env

