name: Weekly Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 5'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up GitHub CLI
      uses: actions/setup-gh@v0
      with:
        cli-version: '2.x'

    - name: Create Release
      run: |
        gh release create v${{ github.run_number }} \
          --title "Weekly Release \
          --generate-notes"

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
