on:
    push:
      branches:
        - report_changes
    workflow_dispatch:
  
  
name: Report
  
jobs:
  
    build_latex:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Git repository
          uses: actions/checkout@v3

        - name: Compile LaTeX document
          uses: xu-cheng/latex-action@v2
          with:
            root_file: report/main.tex

        - name: Move PDF to build directory
          run: |
              mkdir -p report/build
              mv main.pdf report/build/
            
        - name: Upload PDF file
          uses: actions/upload-artifact@v3
          with: 
            name: PDF
            path: report/build/main.pdf