on:
  push:
    paths:
      - 'report/**'
  workflow_dispatch:

name: Report

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            cd ./report
            pdflatex -output-directory build main.tex 

      - name: Move PDF to build directory
        run: |
          mkdir -p report/build
          mv main.pdf report/build/MSc_group_o.pdf

      - name: Commit and push generated PDF
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add report/build/MSc_group_o.pdf
          git commit -m 'Add generated MSc_group_o.pdf'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with: 
          name: PDF
          path: report/build/MSc_group_o.pdf
